// MyndGuard Encrypted Configuration
// Do not edit this file manually
// Emails are managed by users inside the app
const MYNDGUARD_ENCRYPTED = "IG7HLkwVaQ1GpQfHev7pzGzr7GVe3NKkLdn5GElPXH3uTpc6KancExdRpBlRiwtBVdx2dXV8utHR0EJ9V+mJBJG30XDll1kheukCaqGcY3h4Iw8TuSWup/MZypJm8CsX3xH6sL1zIuDhB8Ok2raGYJjmVyG4N/UlJEhur3pVOWJbf2Cjd2IDQN4BJ9G+X4q6h9U58nOdP3fC07AvWiXsuXvRCFcQl4VtbjDjZZ4Y3b2jsn6BYeSlRsAyoxpaDLGfMLIJmTEmCyraN5usutKPH3qGMXU/wuwcru2x3HQw6yP+fg2b+U8aBQ==";
const MYNDGUARD_CONFIG = null; // Loaded at runtime